package com.lge.config;

import generated.ConfigBuildBase;

public class ConfigBuildFlags extends ConfigBuildBase {
    public static final boolean CAPP_ALMOND;
    public static final boolean CAPP_BUBBLE_POPUP;
    public static final boolean CAPP_CAMERA_BURSTSHOT;
    public static final boolean CAPP_CLIPTRAY;
    public static final boolean CAPP_CUPSS;
    public static final boolean CAPP_DIVX_DRM;
    public static final boolean CAPP_DRM;
    public static final boolean CAPP_DSDA;
    public static final boolean CAPP_EMERALDUI;
    public static final boolean CAPP_EMOJI;
    public static final boolean CAPP_EMOJI_DCM;
    public static final boolean CAPP_FONTS;
    public static final boolean CAPP_FONTS_JP;
    public static final boolean CAPP_FONTS_MID;
    public static final boolean CAPP_FONTS_MID_HINT;
    public static final boolean CAPP_FONTS_SMALLER;
    public static final boolean CAPP_FONTS_SMALLER_HINT;
    public static final boolean CAPP_HDMI_AUDIO_INFO = false;
    public static final boolean CAPP_KEYLED_TIMEOUT;
    public static final boolean CAPP_LED_MANAGER;
    public static final boolean CAPP_LGEVPN;
    public static final boolean CAPP_LGEVPN_3_0;
    public static final boolean CAPP_MDM;
    public static final boolean CAPP_MM_MTK;
    public static final boolean CAPP_MOVE_SDCARD;
    public static final boolean CAPP_MULTISIM;
    public static final boolean CAPP_NFC;
    public static final boolean CAPP_ONECOLORLED_VZW;
    public static final boolean CAPP_OPTIMUSUI;
    public static final boolean CAPP_OSP = false;
    public static final boolean CAPP_QHD;
    public static final boolean CAPP_QWINDOW;
    public static final boolean CAPP_RESOURCE;
    public static final boolean CAPP_SDENCRYPTION;
    public static final boolean CAPP_SDENCRYPTION_USERKEY;
    public static final boolean CAPP_SECUREBOOT;
    public static final boolean CAPP_SMARTCARD;
    public static final boolean CAPP_SMARTCARD_OMA;
    public static final boolean CAPP_TALKBACKQUICKACCESS;
    public static final boolean CAPP_THEMEICON;
    public static final boolean CAPP_TOUCHCONTROL;
    public static final boolean CAPP_TRIMHEAPS = false;
    public static final boolean CAPP_UPLUSAPI;
    public static final boolean CAPP_VOLUME_VIBRATOR;
    public static final boolean CAPP_WAPSERVICE;
    public static final boolean CAPP_WFDS_ASP;
    public static final boolean CAPP_WFDS_SEND;

    static {
        CAPP_DRM = ConfigBuildBase.CAPP_DRM;
        CAPP_MDM = ConfigBuildBase.CAPP_MDM;
        CAPP_QHD = ConfigBuildBase.CAPP_QHD;
        CAPP_FONTS = ConfigBuildBase.CAPP_FONTS;
        CAPP_FONTS_MID = ConfigBuildBase.CAPP_FONTS_MID;
        CAPP_FONTS_SMALLER = ConfigBuildBase.CAPP_FONTS_SMALLER;
        CAPP_FONTS_MID_HINT = ConfigBuildBase.CAPP_FONTS_MID_HINT;
        CAPP_FONTS_SMALLER_HINT = ConfigBuildBase.CAPP_FONTS_SMALLER_HINT;
        CAPP_FONTS_JP = ConfigBuildBase.CAPP_FONTS_JP;
        CAPP_LED_MANAGER = ConfigBuildBase.CAPP_LED_MANAGER;
        CAPP_BUBBLE_POPUP = ConfigBuildBase.CAPP_BUBBLE_POPUP;
        CAPP_VOLUME_VIBRATOR = ConfigBuildBase.CAPP_VOLUME_VIBRATOR;
        CAPP_ALMOND = ConfigBuildBase.CAPP_ALMOND;
        CAPP_SDENCRYPTION = ConfigBuildBase.CAPP_SDENCRYPTION;
        CAPP_SDENCRYPTION_USERKEY = ConfigBuildBase.CAPP_SDENCRYPTION_USERKEY;
        CAPP_MOVE_SDCARD = ConfigBuildBase.CAPP_MOVE_SDCARD;
        CAPP_WAPSERVICE = ConfigBuildBase.CAPP_WAPSERVICE;
        CAPP_CUPSS = ConfigBuildBase.CAPP_CUPSS;
        CAPP_RESOURCE = ConfigBuildBase.CAPP_RESOURCE;
        CAPP_SMARTCARD = ConfigBuildBase.CAPP_SMARTCARD;
        CAPP_SMARTCARD_OMA = ConfigBuildBase.CAPP_SMARTCARD_OMA;
        CAPP_THEMEICON = ConfigBuildBase.CAPP_THEMEICON;
        CAPP_SECUREBOOT = ConfigBuildBase.CAPP_SECUREBOOT;
        CAPP_OPTIMUSUI = ConfigBuildBase.CAPP_OPTIMUSUI;
        CAPP_QWINDOW = ConfigBuildBase.CAPP_QWINDOW;
        CAPP_DIVX_DRM = ConfigBuildBase.CAPP_DIVX_DRM;
        CAPP_CLIPTRAY = ConfigBuildBase.CAPP_CLIPTRAY;
        CAPP_TOUCHCONTROL = ConfigBuildBase.CAPP_TOUCHCONTROL;
        CAPP_TALKBACKQUICKACCESS = ConfigBuildBase.CAPP_TALKBACKQUICKACCESS;
        CAPP_EMOJI = ConfigBuildBase.CAPP_EMOJI;
        CAPP_EMOJI_DCM = ConfigBuildBase.CAPP_EMOJI_DCM;
        CAPP_NFC = ConfigBuildBase.CAPP_NFC;
        CAPP_KEYLED_TIMEOUT = ConfigBuildBase.CAPP_KEYLED_TIMEOUT;
        CAPP_MULTISIM = ConfigBuildBase.CAPP_MULTISIM;
        CAPP_LGEVPN = ConfigBuildBase.CAPP_LGEVPN;
        CAPP_LGEVPN_3_0 = ConfigBuildBase.CAPP_LGEVPN_3_0;
        CAPP_UPLUSAPI = ConfigBuildBase.CAPP_UPLUSAPI;
        CAPP_CAMERA_BURSTSHOT = ConfigBuildBase.CAPP_CAMERA_BURSTSHOT;
        CAPP_EMERALDUI = ConfigBuildBase.CAPP_EMERALDUI;
        CAPP_WFDS_ASP = ConfigBuildBase.CAPP_WFDS_ASP;
        CAPP_WFDS_SEND = ConfigBuildBase.CAPP_WFDS_SEND;
        CAPP_ONECOLORLED_VZW = ConfigBuildBase.CAPP_ONECOLORLED_VZW;
        CAPP_MM_MTK = ConfigBuildBase.CAPP_MM_MTK;
        CAPP_DSDA = ConfigBuildBase.CAPP_DSDA;
    }
}
